import * as THREE from 'three';
import createCoupe from './assets/rescue_candidates/player/player_a.js';
import createFestivalKit from './assets/rescue_candidates/environment/environment_b.js';
import { awardRace, rankedStandings, RACES, RIVAL_TUNING, stepCar, type CarState, type RivalId, type Standing } from './race';
import './styles.css';

const $=<T extends Element>(q:string)=>document.querySelector<T>(q)!;
const app=$<HTMLDivElement>('#app');
app.innerHTML=`<main id="menu" class="screen"><section class="card hero"><p class="kicker">THE CANTERA HILL-CLIMB · 1982</p><h1>ROAD<br><i>ZERO</i></h1><p class="lede">Three rivals. Three roads. Learn how they race.</p><div class="actions"><button id="championship" class="primary">START CHAMPIONSHIP</button><button id="quick">QUICK RACE</button><button id="how">HOW TO PLAY</button></div><p class="keys">WASD / ARROWS · SPACE HANDBRAKE · R RESET · ESC PAUSE</p></section></main>
<section id="brief" class="screen hidden"><div class="card modal"><p class="kicker">DRIVER BRIEFING</p><h2>READ THE RIVALS</h2><p><b class="charger">CHARGER</b> dives late and can overcommit. <b class="technician">TECHNICIAN</b> owns the clean line. <b class="defender">DEFENDER</b> protects position without weaving.</p><p>Brake before the bend, turn in, then accelerate out. Grass costs speed. Tap the handbrake to rotate.</p><button id="close" class="primary">GOT IT</button></div></section>
<section id="preRace" class="screen hidden"><div class="card"><p id="round" class="kicker"></p><h2 id="raceName"></h2><p id="raceCopy" class="lede"></p><button id="grid" class="primary">TO THE GRID</button></div></section>
<div id="hud" class="hidden"><div class="plate"><b id="position">1 / 4</b><small>POSITION</small></div><div class="plate center"><b id="lap">1 / 2</b><small>LAP</small></div><div class="plate right"><b id="speed">000</b><small>KM/H</small></div><div id="raceLabel"></div><div id="countdown"></div><div id="notice"></div></div>
<div id="touch" class="hidden"><div id="steerPad"><span id="steerKnob"></span></div><div class="pedals"><button id="brake">BRAKE</button><button id="throttle">GO</button><button id="handbrake">SLIP</button></div></div>
<section id="results" class="screen hidden"><div class="card results-card"><p id="resultKicker" class="kicker"></p><h2 id="resultTitle"></h2><div id="raceOrder"></div><h3>CHAMPIONSHIP</h3><div id="standings"></div><button id="next" class="primary">NEXT RACE</button><button id="menuButton">MAIN MENU</button></div></section>`;

const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.55));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;app.prepend(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8aa6ad);scene.fog=new THREE.Fog(0xb7b6a0,115,350);const camera=new THREE.PerspectiveCamera(56,innerWidth/innerHeight,.1,650);
scene.add(new THREE.HemisphereLight(0xa9c3c3,0x79533f,1.65));const sun=new THREE.DirectionalLight(0xffd39a,3.3);sun.position.set(-55,80,-35);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const C={cream:0xefe1c6,orange:0xc86845,ochre:0xd5a23b,green:0x53694c,sage:0x849077,blue:0x507d92,road:0x343537,stone:0xa88869,earth:0x79533f};const mat=(color:number,r=.85)=>new THREE.MeshStandardMaterial({color,roughness:r,metalness:0});
const ground=new THREE.Mesh(new THREE.CircleGeometry(330,96),mat(0x8b8763,1));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const layoutConfig=[{points:10,radius:73,wave:9,phase:.2},{points:12,radius:70,wave:14,phase:1.1},{points:12,radius:76,wave:12,phase:2.2}];
function layoutPoints(index:number){const cfg=layoutConfig[index];return Array.from({length:cfg.points},(_,i)=>{const a=i/cfg.points*Math.PI*2-Math.PI/2;const r=cfg.radius+Math.sin(i*1.73+cfg.phase)*cfg.wave+Math.cos(i*.83+index)*4;return new THREE.Vector3(Math.cos(a)*r,1.3+Math.sin(i*.9+index)*2.2,Math.sin(a)*r)})}
let curve:THREE.CatmullRomCurve3,samples:THREE.Vector3[]=[],tangents:THREE.Vector3[]=[],road:THREE.InstancedMesh,edges:THREE.InstancedMesh,scenery=new THREE.Group();const dummy=new THREE.Object3D(),forwardAxis=new THREE.Vector3(0,0,1);
function buildTrack(index:number){if(road)scene.remove(road,edges,scenery);scenery=new THREE.Group();scene.add(scenery);curve=new THREE.CatmullRomCurve3(layoutPoints(index),true,'catmullrom',.35);samples=[];tangents=[];const n=220;road=new THREE.InstancedMesh(new THREE.BoxGeometry(8.2,.18,3.9),mat(C.road,.96),n);edges=new THREE.InstancedMesh(new THREE.BoxGeometry(.28,.12,3.9),mat(C.cream,.8),n*2);road.receiveShadow=true;
 for(let i=0;i<n;i++){const p=curve.getPointAt(i/n),tan=curve.getTangentAt(i/n).setY(0).normalize(),side=new THREE.Vector3(-tan.z,0,tan.x);samples.push(p);tangents.push(tan);dummy.position.copy(p);dummy.quaternion.setFromUnitVectors(forwardAxis,tan);dummy.updateMatrix();road.setMatrixAt(i,dummy.matrix);for(const s of [-1,1]){dummy.position.copy(p).addScaledVector(side,s*4.22);dummy.position.y+=.1;dummy.updateMatrix();edges.setMatrixAt(i*2+(s>0?1:0),dummy.matrix)}}scene.add(road,edges);buildScenery(index)}
function buildScenery(index:number){const trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(.22,.35,2.5,7),mat(0x5e4434,1),42),crowns=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1.5,1),mat(index===1?C.sage:C.green,1),42),rocks=new THREE.InstancedMesh(new THREE.DodecahedronGeometry(1.35),mat(C.stone,1),32),mountains=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,1),mat(index===2?0x59695f:0x657267,1),14);
 for(let i=0;i<42;i++){const k=i*5%220,p=samples[k],tan=tangents[k],side=new THREE.Vector3(-tan.z,0,tan.x),sgn=i%2?1:-1;dummy.position.copy(p).addScaledVector(side,sgn*(9+i*13%10));dummy.position.y=p.y+1.2;dummy.rotation.y=i*2.17;dummy.scale.setScalar(.8+i%5*.08);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);dummy.position.y+=2.5;dummy.scale.set(1+i%3*.14,1.15+i%4*.1,1);dummy.updateMatrix();crowns.setMatrixAt(i,dummy.matrix)}
 for(let i=0;i<32;i++){const k=(i*7+11)%220,p=samples[k],tan=tangents[k],side=new THREE.Vector3(-tan.z,0,tan.x);dummy.position.copy(p).addScaledVector(side,(i%2?1:-1)*(7.8+i%8));dummy.position.y=p.y+.7;dummy.rotation.set(i*.4,i*.77,i*.2);dummy.scale.set(.8+i%4*.35,.65+i%3*.3,1);dummy.updateMatrix();rocks.setMatrixAt(i,dummy.matrix)}
 for(let i=0;i<14;i++){const a=i/14*Math.PI*2,r=165+(i%3)*18;dummy.position.set(Math.sin(a)*r,20+(i%4)*3,Math.cos(a)*r);dummy.rotation.set(i*.08,a+i*.23,i*.04);dummy.scale.set(32+(i%4)*6,42+(i%3)*7,25+(i%5)*4);dummy.updateMatrix();mountains.setMatrixAt(i,dummy.matrix)}scenery.add(trunks,crowns,rocks,mountains);
 const kit=createFestivalKit(THREE),parts=kit.userData.parts as Record<string,THREE.Group>;const placements:[string,number,number,number][]=[['finishLandmark',0,0,0],['marshalHut',7,-1,8],['spectatorCanopy',17,1,10],['timberBarrier',24,-1,6],['villageModule',34,1,13],['spectatorCanopy',48,-1,11],['paddockStructure',73,-1,12],['villageModule',105,1,12],['rockFormation',133,-1,9],['timberBarrier',158,1,7],['hayBale',181,-1,6],['roadsideTree',205,1,10]];for(const [name,k,sgn,away] of placements){const item=parts[name].clone(true),p=samples[k%220],tan=tangents[k%220],side=new THREE.Vector3(-tan.z,0,tan.x);item.position.copy(p).addScaledVector(side,sgn*away);item.position.y=p.y;item.rotation.y=Math.atan2(tan.x,tan.z)+(sgn<0?Math.PI:0);scenery.add(item)}
 for(const k of [11,15,19,23,27,31]){const item=parts.hayBale.clone(true),p=samples[k],tan=tangents[k],side=new THREE.Vector3(-tan.z,0,tan.x);item.position.copy(p).addScaledVector(side,-5.2);item.position.y=p.y;item.rotation.y=Math.atan2(tan.x,tan.z);scenery.add(item)}}

type Racer={id:'PLAYER'|RivalId;car:THREE.Group;progress:number;checkpoint:number;lap:number;speed:number;lane:number;finished:boolean;finishTime:number};const accents={PLAYER:0xd74b3f,CHARGER:0xd7a72f,TECHNICIAN:0x3f7390,DEFENDER:0x617b4e};
function makeCar(id:keyof typeof accents){const car=createCoupe(THREE);car.name=id;car.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;if(o.material?.name?.startsWith('red-enamel')){o.material=o.material.clone();o.material.color.setHex(accents[id])}}});const paint=mat(accents[id],.34),dark=mat(0x353a3b,.8);if(id==='CHARGER'){car.scale.set(1.02,.94,1.04);const wing=new THREE.Mesh(new THREE.BoxGeometry(1.3,.08,.3),paint);wing.position.set(0,.93,-1.55);car.add(wing)}if(id==='TECHNICIAN'){car.scale.set(.98,1,1);const splitter=new THREE.Mesh(new THREE.BoxGeometry(1.45,.09,.28),dark);splitter.position.set(0,.24,1.77);car.add(splitter)}if(id==='DEFENDER'){car.scale.set(1.04,1.02,.96);const deck=new THREE.Mesh(new THREE.BoxGeometry(1.25,.13,.55),paint);deck.position.set(0,.82,-1.28);car.add(deck)}scene.add(car);return car}
const playerCar=makeCar('PLAYER'),rivalCars=(['CHARGER','TECHNICIAN','DEFENDER'] as RivalId[]).map(makeCar);let racers:Racer[]=[],player:CarState={speed:0,heading:0,slip:0,steerAngle:0,x:0,z:0,offroad:false};let mode:'championship'|'quick'='championship',raceIndex=0,racing=false,paused=false,countdown=0,raceClock=0,last=performance.now(),fps=60,frames=0,fpsStamp=last;let standings:Standing[]=[];const keys=new Set<string>();let touchSteer=0,touchThrottle=0,touchBrake=0,touchHandbrake=false;
const freshStandings=()=>['PLAYER','CHARGER','TECHNICIAN','DEFENDER'].map(id=>({id,points:0,wins:0,bestFinish:99,lastFinish:99}));
function nearest(pos:THREE.Vector3){let best=Infinity,idx=0;for(let i=0;i<samples.length;i++){const d=pos.distanceToSquared(samples[i]);if(d<best){best=d;idx=i}}return{t:idx/samples.length,distance:Math.sqrt(best),idx}}
function place(r:Racer,t:number,lane:number){const p=curve.getPointAt((t+1)%1),tan=curve.getTangentAt((t+1)%1).setY(0).normalize(),side=new THREE.Vector3(-tan.z,0,tan.x);r.car.position.copy(p).addScaledVector(side,lane);r.car.position.y+=.14;r.car.rotation.y=Math.atan2(tan.x,tan.z)}
function showPreRace(){const race=RACES[raceIndex];$('#menu').classList.add('hidden');$('#results').classList.add('hidden');$('#preRace').classList.remove('hidden');$('#round').textContent=`ROUND ${raceIndex+1} OF 3`;$('#raceName').textContent=race.name;$('#raceCopy').textContent=["Flowing orchard bends reward courage — and punish the Charger's impatience.","Broken stone and tight exits give the Technician clean air to exploit.","Summit switchbacks make every pass against the Defender a plan."][raceIndex]}
function resetRace(){buildTrack(raceIndex);raceClock=0;countdown=3.7;racing=true;paused=false;$('#preRace').classList.add('hidden');$('#results').classList.add('hidden');$('#hud').classList.remove('hidden');$('#touch').classList.toggle('hidden',!matchMedia('(pointer:coarse)').matches);racers=[{id:'PLAYER',car:playerCar,progress:.005,checkpoint:0,lap:1,speed:0,lane:-1.4,finished:false,finishTime:0},...rivalCars.map((car,i)=>({id:(['CHARGER','TECHNICIAN','DEFENDER'] as RivalId[])[i],car,progress:.994-i*.008,checkpoint:3,lap:0,speed:0,lane:[1.35,-1.35,1.35][i],finished:false,finishTime:0}))];racers.forEach(r=>place(r,r.progress,r.lane));const p=playerCar.position;player={speed:0,heading:playerCar.rotation.y,slip:0,steerAngle:0,x:p.x,z:p.z,offroad:false};updateHud()}
function updateHud(){const p=racers[0],rank=p?1+racers.filter(r=>r!==p&&(r.lap+r.progress)>(p.lap+p.progress)).length:1;$('#position').textContent=`${rank} / 4`;$('#lap').textContent=`${Math.min(p?.lap||1,2)} / 2`;$('#speed').textContent=String(Math.round(Math.abs(player.speed)*3.6)).padStart(3,'0');$('#raceLabel').textContent=RACES[raceIndex].name}
function finishRace(){if(!racing)return;racing=false;const order=[...racers].sort((a,b)=>a.finished===b.finished?(a.finished?a.finishTime-b.finishTime:(b.lap+b.progress)-(a.lap+a.progress)):a.finished?-1:1).map(r=>r.id);if(mode==='championship')standings=awardRace(standings,order);const rank=order.indexOf('PLAYER')+1,final=mode==='championship'&&raceIndex===2,table=rankedStandings(standings);$('#resultKicker').textContent=`${RACES[raceIndex].name} · ${[10,7,4,2][rank-1]} POINTS`;$('#resultTitle').textContent=final?(table[0].id==='PLAYER'?'HILL-CLIMB CHAMPION':'CHAMPIONSHIP COMPLETE'):(rank===1?'STAGE WIN':'RACE COMPLETE');$('#raceOrder').innerHTML=order.map((id,i)=>`<div><span>${i+1}</span><b class="${id.toLowerCase()}">${id}</b></div>`).join('');$('#standings').innerHTML=table.map((s,i)=>`<div><span>${i+1}</span><b>${s.id}</b><em>${s.points} PTS</em></div>`).join('');$('#next').textContent=final?'NEW CHAMPIONSHIP':mode==='quick'?'RACE AGAIN':'NEXT RACE';$('#hud').classList.add('hidden');$('#touch').classList.add('hidden');$('#results').classList.remove('hidden')}
function resetPlayer(){const t=racers[0]?.progress||0,p=curve.getPointAt(t),tan=curve.getTangentAt(t).setY(0).normalize();player={speed:0,heading:Math.atan2(tan.x,tan.z),slip:0,steerAngle:0,x:p.x,z:p.z,offroad:false};playerCar.position.copy(p);playerCar.position.y+=.14}
function update(dt:number){if(!racing||paused)return;raceClock+=dt;if(countdown>0){countdown-=dt;$('#countdown').textContent=countdown>.55?String(Math.ceil(countdown)):'GO!';if(countdown<=0)setTimeout(()=>$('#countdown').textContent='',500);return}const throttle=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)||touchThrottle,brake=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)||touchBrake,steer=(keys.has('KeyA')||keys.has('ArrowLeft')?-1:0)+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)+touchSteer;
 const before=nearest(playerCar.position);player.offroad=before.distance>4.3;player=stepCar(player,{throttle,brake,steer,handbrake:keys.has('Space')||touchHandbrake},dt);const after=nearest(new THREE.Vector3(player.x,0,player.z));playerCar.position.set(player.x,curve.getPointAt(after.t).y+.14,player.z);playerCar.rotation.y=player.heading;playerCar.rotation.z=THREE.MathUtils.damp(playerCar.rotation.z,-player.slip*.22,7,dt);const parts=playerCar.userData.parts;if(parts){parts.wheelFL.rotation.y=player.steerAngle*.22;parts.wheelFR.rotation.y=player.steerAngle*.22;for(const k of ['wheelFL','wheelFR','wheelRL','wheelRR'])parts[k].children.forEach((x:THREE.Object3D)=>x.rotation.x-=player.speed*dt/.31)}const pr=racers[0],prev=pr.progress;pr.progress=after.t;if(pr.checkpoint===0&&after.t>.22&&after.t<.45)pr.checkpoint=1;if(pr.checkpoint===1&&after.t>.47&&after.t<.7)pr.checkpoint=2;if(pr.checkpoint===2&&after.t>.72&&after.t<.94)pr.checkpoint=3;if(prev>.8&&after.t<.2&&pr.checkpoint===3){pr.checkpoint=0;pr.lap++;if(pr.lap>2){pr.finished=true;pr.finishTime=raceClock;finishRace();return}}
 for(let i=1;i<racers.length;i++){const r=racers[i],tune=RIVAL_TUNING[r.id as RivalId];if(r.finished)continue;const bend=curve.getTangentAt((r.progress+.018)%1).angleTo(curve.getTangentAt((r.progress+.045)%1));let target=tune.topSpeed*(1-Math.min(.5,bend*1.35));if(r.id==='CHARGER'&&Math.sin(raceClock*.75+i*4)>.985)target*=1-tune.mistakeLoss;const delta=(pr.lap+pr.progress)-(r.lap+r.progress);if(r.id==='DEFENDER'&&delta<.035&&delta>-.01)r.lane=THREE.MathUtils.damp(r.lane,Math.sign(pr.lane||1)*1.75,3,dt);else if(r.id==='CHARGER'&&Math.abs(delta)<.025)r.lane=THREE.MathUtils.damp(r.lane,-Math.sign(pr.lane||1)*2.1,4,dt);else r.lane=THREE.MathUtils.damp(r.lane,r.id==='TECHNICIAN'?0:(i%2?1.1:-1.1),tune.lineSmoothing,dt);r.speed=THREE.MathUtils.damp(r.speed,target,tune.launch*1.25,dt);r.progress+=r.speed*dt/curve.getLength();if(r.progress>=1){r.progress--;r.lap++;if(r.lap>2){r.finished=true;r.finishTime=raceClock}}place(r,r.progress,r.lane);if(r.car.position.distanceTo(playerCar.position)<1.55){player.speed*=.88;const push=playerCar.position.clone().sub(r.car.position).setY(0).normalize().multiplyScalar(.08);player.x+=push.x;player.z+=push.z}}pr.lane=new THREE.Vector3(player.x,0,player.z).sub(curve.getPointAt(after.t)).dot(new THREE.Vector3(-tangents[after.idx].z,0,tangents[after.idx].x));const dir=new THREE.Vector3(Math.sin(player.heading),0,Math.cos(player.heading)),target=playerCar.position.clone().addScaledVector(dir,-5.6).add(new THREE.Vector3(0,2.7,0));camera.position.lerp(target,1-Math.exp(-5*dt));camera.lookAt(playerCar.position.clone().addScaledVector(dir,8).add(new THREE.Vector3(0,.7,0)));camera.fov=THREE.MathUtils.damp(camera.fov,52+Math.min(10,Math.abs(player.speed)*.23),4,dt);camera.updateProjectionMatrix();updateHud()}

function startChampionship(){mode='championship';raceIndex=0;standings=freshStandings();$('#menu').classList.add('hidden');resetRace()}$('#championship').addEventListener('click',startChampionship);$('#quick').addEventListener('click',()=>{mode='quick';raceIndex=0;standings=freshStandings();$('#menu').classList.add('hidden');resetRace()});$('#grid').addEventListener('click',resetRace);$('#how').addEventListener('click',()=>$('#brief').classList.remove('hidden'));$('#close').addEventListener('click',()=>$('#brief').classList.add('hidden'));$('#menuButton').addEventListener('click',()=>location.reload());$('#next').addEventListener('click',()=>{if(mode==='championship'&&raceIndex<2){raceIndex++;showPreRace()}else if(mode==='championship')startChampionship();else resetRace()});addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='KeyR'&&racing)resetPlayer();if(e.code==='Escape')paused=!paused;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault()});addEventListener('keyup',e=>keys.delete(e.code));
const pad=$<HTMLElement>('#steerPad'),knob=$<HTMLElement>('#steerKnob');function steerTouch(e:PointerEvent){const r=pad.getBoundingClientRect();touchSteer=THREE.MathUtils.clamp((e.clientX-r.left-r.width/2)/(r.width*.38),-1,1);knob.style.transform=`translateX(${touchSteer*38}px)`}pad.addEventListener('pointerdown',e=>{pad.setPointerCapture(e.pointerId);steerTouch(e)});pad.addEventListener('pointermove',e=>{if(pad.hasPointerCapture(e.pointerId))steerTouch(e)});pad.addEventListener('pointerup',()=>{touchSteer=0;knob.style.transform='' });for(const [id,set] of [['throttle',(v:number)=>touchThrottle=v],['brake',(v:number)=>touchBrake=v],['handbrake',(v:number)=>touchHandbrake=!!v]] as const){const el=$<HTMLElement>(`#${id}`);el.addEventListener('pointerdown',e=>{el.setPointerCapture(e.pointerId);set(1)});el.addEventListener('pointerup',()=>set(0));el.addEventListener('pointercancel',()=>set(0))}
function frame(now:number){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);renderer.render(scene,camera);frames++;if(now-fpsStamp>600){fps=frames*1000/(now-fpsStamp);frames=0;fpsStamp=now}const p=racers[0];window.__GAME__={pos:[playerCar.position.x,playerCar.position.z],fps,speed:player.speed,score:standings.find(s=>s.id==='PLAYER')?.points||0,over:!racing&&!!p,draws:renderer.info.render.calls,tris:renderer.info.render.triangles,progress:p?.progress||0,drift:Math.abs(player.slip),route:RACES[raceIndex].id,construction:0,modules:1,heading:player.heading,position:p?1+racers.filter(r=>r!==p&&(r.lap+r.progress)>(p.lap+p.progress)).length:1,aiProgress:racers.slice(1).map(r=>r.progress),mode}}
addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.55));camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()});buildTrack(0);const preview:Racer={id:'PLAYER',car:playerCar,progress:0,checkpoint:0,lap:1,speed:0,lane:0,finished:false,finishTime:0};place(preview,0,0);rivalCars.forEach((car,i)=>place({...preview,car},.03+i*.015,(i-1)*1.5));camera.position.set(0,5,-95);camera.lookAt(0,1,-75);standings=freshStandings();window.__READY__=true;window.__START__=resetRace;window.__GAME__={pos:[0,0],fps:0,speed:0,score:0,over:false,draws:0,tris:0,progress:0,drift:0,route:'MENU',construction:0,modules:1,heading:0};frame(performance.now());
